### ISSUE TITLE
Error importing pins in Python: 'No such file or directory /pins/js/pins.js'

### ISSUE THREAD

**Issue by chuktuk** [pinsjs/pinsjs#42]
I followed the installations instructions at https://pinsjs.github.io/pinsjs/ to install pins in python, and when I try to run import pins I get a file not found error.

![image](https://user-images.githubusercontent.com/45741689/105407718-10ff8700-5bfc-11eb-8e8e-491f685ee401.png)

![image](https://user-images.githubusercontent.com/45741689/105407767-207ed000-5bfc-11eb-88df-c793704c6535.png)

![image](https://user-images.githubusercontent.com/45741689/105407827-2eccec00-5bfc-11eb-9bf6-c88aab8552e2.png)

![image](https://user-images.githubusercontent.com/45741689/105407937-54f28c00-5bfc-11eb-8ba5-4130d6ca794f.png)

**Comment by javierluraschi** [comment]
Yikes let me fix that right away!

**Comment by javierluraschi** [comment]
Fixed with https://github.com/pinsjs/pinsjs/commit/80f7e602663d67353cddcd3a263b1914a505ef20, please run:

```
pip3 uninstall pins
```

Followed by re-installing, thanks!
